name: flutter_works
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^1.0.2
  dartz: ^0.9.2
  dio: ^4.0.0
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  get_it: ^6.1.1
  hive: ^2.0.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.1
  very_good_analysis: ^2.0.3

flutter:
  uses-material-design: true
  generate: true
