name: flutter_works
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  auto_route: ^3.2.0
  dartz: ^0.10.1
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  hive: ^2.0.5
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  path_provider: ^2.0.8

dev_dependencies:
  auto_route_generator: ^3.2.0
  bloc_test: ^9.0.1
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.3
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/flags/